# This is a basic workflow to help you get started with Actions

name: simple-lyra-test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: ["testing-actions"]
  pull_request:
    branches: ["testing-actions"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test-lyra:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Clone repository
        run: git clone https://github.com/raifcoonjah/lyra.git
      - name: Enter repository
        run: cd lyra
      - name: Test lyra execution
        run: |
          if ./lyra.sh; then
            echo "Success! lyra.sh executed."
            sleep 5
          else
            echo "Error: lyra.sh did not execute."
          fi
